from .login import router as login_router
from .users import router as users_router
from .employees import router as employees_router
from .exercises import router as exercises_router
from .api import router as api_router
from .complexes import router as complexes_router
from .courses import router as courses_router
from .mailing import router as mailing_router
from .index import router as index_router
from .motivation import router as motivation_router
